### ISSUE TITLE
Address RSpec deprecation warnings

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#125]
```
Deprecation Warnings:

Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/temikus/Code/vagrant-dev/vagrant-google/test/unit/common/config_test.rb:33:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/temikus/Code/vagrant-dev/vagrant-google/test/unit/common/config_test.rb:34:in `block (2 levels) in <top (required)>'.
Use of rspec-core's `its` method is deprecated. Use the rspec-its gem instead. Called from /Users/temikus/Code/vagrant-dev/vagrant-google/test/unit/common/config_test.rb:35:in `block (2 levels) in <top (required)>'.
Too many uses of deprecated 'Use of rspec-core's `its` method'. Pass `--deprecation-out` or set `config.deprecation_stream` to a file for full output.

`be_false` is deprecated. Use `be_falsey` (for Ruby's conditional semantics) or `be false` (for exact `== false` equality) instead. Called from /Users/temikus/Code/vagrant-dev/vagrant-google/test/unit/common/config_test.rb:45:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
```

**Comment by Temikus** [comment]
Adressed in #178
