### ISSUE TITLE
trouble getting started

### ISSUE THREAD

**Issue by vinhdizzo** [mitchellh/vagrant-google#126]
Hi,

I'm trying vagrant-google on a Windows 7 laptop with cygwin.  I followed the README and created a Vagrantfile for GCE, added the GCE box, and set up credentials on the Google side.  My Vagrantfile looks like:

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  config.vm.provider :google do |google, override|
    google.google_project_id = "project-id"
    google.google_client_email = "address@project-id.iam.gserviceaccount.com"
    google.google_json_key_location = "~/vagrant_google_test/My First Project-numbers.json"
    google.image = "ubuntu-14-04"
    google.machine_type= "n1-standard-1"

    override.ssh.username = "vinh"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
    #override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

end
```

I errors/warnings when trying to start things up:

``` sh
$ vagrant up --provider=google
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:91:in `block in action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `tap'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:29:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:187:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:45:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:183:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:89:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:278:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:276:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:275:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/up/command.rb:88:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'

local_user@local-laptop ~/vagrant_google_test
$ vagrant ssh
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:91:in `block in action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `tap'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:29:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:187:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:45:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/ssh/command.rb:41:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'

local_user@local-laptop ~/vagrant_google_test
$ vagrant destroy
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml.rb:2:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/fog-google-0.0.9/lib/fog/google.rb:3:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `require'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:14:in `<top (required)>'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:91:in `block in action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `tap'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/action.rb:89:in `action_read_state'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:29:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:187:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from C:/Users/local_user/.vagrant.d/gems/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:45:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:501:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:144:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:663:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/commands/destroy/command.rb:30:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:302:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:174:in `<main>'
```

Any thoughts on what's going on?  Is vagrant-google not supported on Windows or Cygwin perhaps?    Thanks for your help.

**Comment by Temikus** [comment]
Hey @vinhdizzo!

Hmmm, the issue is because it cannot load `nokogiri` gem, which is required by `fog-xml`, which is required by `fog-google`. Considering that nokogiri does need to compile native extensions during install, its' install may have failed in cygwin environment. Were there errors displayed during `vagrant plugin install`?

If none - can you try to uninstall the plugin and reinstall it again in verbose mode and paste the log here?
```
vagrant plugin uninstall vagrant-google
vagrant plugin install --verbose vagrant-google
```

Cheers,
A.

**Comment by vinhdizzo** [comment]
Here's the log to the re-install:
```sh
$ vagrant plugin install --verbose vagrant-google
Installing the 'vagrant-google' plugin. This can take a few minutes...
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
Fetching source index from http://gems.hashicorp.com/
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/......
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Using i18n 0.7.0
Installing json 1.8.3 with native extensions
Installing minitest 5.8.4
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.5.2
Installing addressable 2.4.0
Installing extlib 0.9.16
Installing multi_json 1.11.0
Installing autoparse 0.3.3
Using builder 3.2.2
Using bundler 1.10.6
Using ffi 1.9.10
Using childprocess 0.5.9
Using erubis 2.7.0
Installing excon 0.47.0
Installing multipart-post 2.0.0
Installing faraday 0.9.2
Installing formatador 0.2.5
Installing fog-core 1.36.0
Installing fog-json 1.0.2
Using mini_portile 0.6.0
Using nokogiri 1.6.3.1
Installing fog-xml 0.1.2
Installing fog-google 0.0.9
Installing jwt 1.5.3
Using little-plugger 1.1.4
Using logging 1.8.2
Installing memoist 0.14.0
Installing signet 0.7.2
Installing googleauth 0.4.0
Installing launchy 2.4.3
Installing retriable 1.4.1
Installing google-api-client 0.8.6
Using gssapi 1.2.0
Using gyoku 1.3.1
Using hashicorp-checkpoint 0.1.4
Using httpclient 2.7.1
Using rb-fsevent 0.9.6
Using rb-inotify 0.9.5
Using listen 3.0.5
Using log4r 1.1.10
Using mime-types 1.25.1
Using net-ssh 3.0.2
Using net-scp 1.1.2
Using net-sftp 2.1.2
Using nori 2.6.0
Using rb-kqueue 0.2.4
Using rest-client 1.6.9
Using rubyntlm 0.4.0
Using rubyzip 1.1.7
Using uuidtools 2.1.5
Using wdm 0.1.1
Using winrm 1.3.6
Using winrm-fs 0.2.3
Using vagrant 1.8.1
Installing vagrant-google 0.2.3
Using vagrant-share 1.1.5
Installed the plugin 'vagrant-google (0.2.3)'!
```

Same errors persist.

**Comment by vinhdizzo** [comment]
I tried these commands using `cmd.exe` instead of a cygwin terminal, and I get the same errors.

**Comment by Temikus** [comment]
@vinhdizzo Looks like it's a nokogiri issue:
https://github.com/sparklemotion/nokogiri/issues/1256
, which is a hard dependency:
```
    vagrant (= 1.7.4) ruby depends on
      nokogiri (= 1.6.3.1) ruby
```
Looks, like it's going to be fixed in vagrant 1.8.1+:
https://github.com/mitchellh/vagrant/issues/6766

**Comment by vinhdizzo** [comment]
I can't find any information on when 1.8.1 is going to come out...

Do you know where I could find an installer for the dev version (no ruby experience)?  Or do you know which older version of vagrant might work for me to try?  Thanks.

**Comment by Temikus** [comment]
@vinhdizzo If you have no ruby experience, there's no easy installer for the dev version, I'm afraid.
If I were you I would start looking into using a linux vm, maybe a vagrant machine to speed things up (I know it's meta, but at least it's going to be easy for you, as you can develop locally and not fiddle with the shared folders, etc).

**Comment by vinhdizzo** [comment]
You don't think using vagrant 1.7.4 would work with vagrant-google?

**Comment by vinhdizzo** [comment]
Regarding the last suggestion, are you suggesting I use vagrant to start a linux vm with vagrant?  Then from there, try out vagrant-google?  I suppose that is reasonable.  Is there a linux box/image that has vagrant installed so that I just need to provision vagrant-cloud?  Thanks.

**Comment by Temikus** [comment]
@vinhdizzo It will work, but not on windows, I'm afraid.
This is not a problem with vagrant-google, but rather a problem with nokogiri and vagrant 1.7.4 dependency lock, which I have no control over, sorry :(

Yes, it seems it may be easier for you to try with a linux VM at first. I don't know about any images with built-in vagrant installer, but it should be fairly trivial to add one line to install a package to the distro in your vagrantfile, see: https://www.vagrantup.com/docs/provisioning/shell.html
You can follow the official guide to get started: https://www.vagrantup.com/docs/getting-started/

Cheers!

**Comment by Temikus** [comment]
@vinhdizzo - It seems that we've sorted this out so I'm going to close this. If you have any issues with the provider itself - feel free to reopen though.

/CC @erjohnso - This should be resolved.

**Comment by vinhdizzo** [comment]
@Temikus I was planning to close this out when the next version of Vagrant is released so I can confirm this works.  Thanks

**Comment by Temikus** [comment]
@vinhdizzo SGTM

**Comment by Temikus** [comment]
@vinhdizzo Just to check up on this - new Vagrant has been released. Did you have a chance to check?

**Comment by Temikus** [comment]
I'm closing this issue since this looks resolved.
However, if you still have any questions - no worries at all - just reopen and I'll help you right out!
