### ISSUE TITLE
Upgraded to vagrant 1.9.0 and cannot install vagrant-google

### ISSUE THREAD

**Issue by cvle** [mitchellh/vagrant-google#157]
I just upgraded to vagrant 1.9.0 and vagrant-google fails to reinstall for some reason..

```bash
$ vagrant plugin install vagrant-google
Installing the 'vagrant-google' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'addressable' (~> 2.3) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems', execute `gem env` for more information
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:319:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:244:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:97:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/bin/vagrant:123:in `<main>'
```

**Comment by Temikus** [comment]
@cvle ACK 1.9.1 was shortly released to fix some issues.

Cannot reproduce in `1.9.1`, can you try upgrading?
```
temikus λ vagrant plugin install vagrant-google
Installing the 'vagrant-google' plugin. This can take a few minutes...
Fetching: formatador-0.2.5.gem (100%)
Fetching: excon-0.54.0.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: jwt-1.5.6.gem (100%)
Fetching: multipart-post-2.0.0.gem (100%)
Fetching: faraday-0.10.0.gem (100%)
Fetching: public_suffix-2.0.4.gem (100%)
Fetching: addressable-2.5.0.gem (100%)
Fetching: signet-0.7.3.gem (100%)
Fetching: thread_safe-0.3.5.gem (100%)
Fetching: minitest-5.10.1.gem (100%)
Fetching: tzinfo-1.2.2.gem (100%)
Fetching: os-0.9.6.gem (100%)
Fetching: memoist-0.15.0.gem (100%)
Fetching: activesupport-4.2.7.1.gem (100%)
Fetching: retriable-1.4.1.gem (100%)
Fetching: launchy-2.4.3.gem (100%)
Fetching: extlib-0.9.16.gem (100%)
Fetching: autoparse-0.3.3.gem (100%)
Fetching: googleauth-0.5.1.gem (100%)
Fetching: fog-xml-0.1.2.gem (100%)
Fetching: fog-json-1.0.2.gem (100%)
Fetching: google-api-client-0.8.7.gem (100%)
Fetching: fog-google-0.4.2.gem (100%)
Fetching: vagrant-google-0.2.5.gem (100%)
Installed the plugin 'vagrant-google (0.2.5)'!
2.1.7 ~/.dotfiles  (master)[17:22:38]∞
temikus λ vagrant --version
Vagrant 1.9.1
```

**Comment by cvle** [comment]
Works in `1.9.1` 👍
