### ISSUE TITLE
Unable to install 2.6.0 on current vagrant

### ISSUE THREAD

**Issue by dcode** [mitchellh/vagrant-google#253]
I'm trying to install the plugin on my system, but the latest few releases fail to install.

Environment:

Vagrant 2.2.17
macOS 11.4

By default only `2.2.0` gets installed if I just to `vagrant plugin install vagrant-google`. If I try to specify the version, I get roughly the same errors:

```
>_ vagrant plugin install vagrant-google --plugin-version="2.6.0"
Installing the 'vagrant-google --version '2.6.0'' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/exceptions.rb:32:in `conflicting_dependencies'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/exceptions.rb:26:in `initialize'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:586:in `internal_install'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:350:in `install'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `each'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `fog-google (~> 1.12.0)` required by `vagrant-google-2.6.0`
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
	from <internal:kernel>:90:in `tap'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
	from /opt/vagrant/embedded/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:586:in `internal_install'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/bundler.rb:350:in `install'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/warden.rb:48:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/builder.rb:149:in `call'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/action/runner.rb:89:in `run'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `each'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:231:in `<main>'
```

## Ideas

I'm not a ruby guy, but I tried to build from source and that also failed. I can only assume this has to do with `fog-google` rapid development from `1.12.0` back in Dec 2020 to now being `1.15.0`.

**Comment by dcode** [comment]
So, I ran ```vagrant plugin install vagrant-google --plugin-version "2.6.0"``` on another macOS 11.4 system and it ran with no problem. In that case, vagrant was version `2.2.16`.

**Comment by Temikus** [comment]
I think the problem is that the plugin doesn't support Ruby 3.0, but in my installation of Vagrant I get only 2.7.0...

```
temikus λ vagrant --version                                                                                                                                           (130)
Vagrant 2.2.19
 ruby: 2.7.4 go: 1.15.7 ~/Dropbox/Code/vagrant-google  (master)-code@temik.me [11:55:10]
temikus λ /opt/vagrant/embedded/bin/ruby --version
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin19
```

@dcode is the first system an M1(ARM) Mac by any chance?

**Comment by Temikus** [comment]
Just tested on Ruby 3.0 and it seems to work now 🤔 Let's release and check.

**Comment by dcode** [comment]
I don't recall, but I'll try the new release next week. This system is x86_64.
