### ISSUE TITLE
Implement service account definitions

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#46]
Seems like a good idea to implement this for when we have applications running within instances that need to programmatically talk between services. It's already implemented in Fog ( `attribute :service_accounts` ) so should be easy to bridge over.

**Comment by Temikus** [comment]
#67 Submitted, need to add documentation.

**Comment by Temikus** [comment]
Need to add validation to make sure the passed attribute is an array, otherwise it traces back:

```
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-1.29.0/lib/fog/google/models/compute/server.rb:244:in `save': undefined method `map' for "https://www.googleapis.com/auth/devstorage.full_control":String (NoMethodError)
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-core-1.30.0/lib/fog/core/collection.rb:51:in `create'
	from /home/temikus/code/vagrant-google/lib/vagrant-google/action/run_instance.rb:136:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/code/vagrant-google/lib/vagrant-google/action/warn_networks.rb:28:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/code/vagrant-google/lib/vagrant-google/action/sync_folders.rb:33:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/code/vagrant-google/lib/vagrant-google/action/connect_google.rb:47:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:214:in `action_raw'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:191:in `block in action'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/environment.rb:516:in `lock'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `call'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `action'
	from /home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
