### ISSUE TITLE
'vagrant destroy' can be run without a running instance

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#50]
One can call `vagrant destroy` on an already destroyed instance.

```
λ vagrant up                                                                                                                                  

Bringing machine 'default' up with 'google' provider...
...
==> default: Machine is ready for SSH access!
...
λ vagrant destroy --force
...
==> default: Terminating the instance...
...
λ vagrant destroy --force
...
/Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:340:in `block (2 levels) in validate_parameters': Parameter 'instance' has an invalid value: . Must match: /^[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?$/. (ArgumentError)
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:328:in `each'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:328:in `block in validate_parameters'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:313:in `each'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:313:in `validate_parameters'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:191:in `generate_uri'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/discovery/method.rb:237:in `generate_request'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/request.rb:190:in `to_http_request'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/request.rb:234:in `to_env'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client/request.rb:162:in `send'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:598:in `block in execute!'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/retriable-2.0.2/lib/retriable.rb:53:in `block in retriable'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `each'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `with_index'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `retriable'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.7.1/lib/google/api_client.rb:634:in `execute'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-1.29.0/lib/fog/google/core.rb:171:in `request'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-1.29.0/lib/fog/google/requests/compute/get_server.rb:70:in `get_server'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-1.29.0/lib/fog/google/models/compute/servers.rb:25:in `get'
  from /Users/temikus/Code/vagrant-dev/vagrant-google/lib/vagrant-google/action/terminate_instance.rb:27:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/Code/vagrant-dev/vagrant-google/lib/vagrant-google/action/connect_google.rb:51:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/call.rb:53:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:214:in `action_raw'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:191:in `block in action'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/environment.rb:516:in `lock'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `call'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `action'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/plugins/commands/destroy/command.rb:31:in `block in execute'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/plugin/v2/command.rb:220:in `each'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/plugins/commands/destroy/command.rb:30:in `execute'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/cli.rb:42:in `execute'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/environment.rb:301:in `cli'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/bin/vagrant:174:in `<top (required)>'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bin/vagrant:23:in `load'
  from /Users/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bin/vagrant:23:in `<main>'
```

**Comment by Temikus** [comment]
There are no checks in the destroy action -_-
PR coming soon.
