### ISSUE TITLE
Default instance names issues with multiple instances in the same zone

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant-google#82]
Example vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "gce"

  config.vm.define :wololo1 do |wololo1|

    wololo1.vm.provider :google do |google, override|
        google.google_project_id = "myproject"
        google.google_client_email = "mydevemail@developer.gserviceaccount.com"
        google.google_json_key_location = "mykeypath"

        override.ssh.username = "temikus"
        override.ssh.private_key_path = "~/.ssh/id_rsa"

      google.zone = "europe-west1-d"

      google.zone_config "europe-west1-d" do |zone1d|
        zone1d.image = "debian-7-wheezy-v20150127"
        zone1d.zone = "europe-west1-d"
        zone1d.disk_type = "pd-ssd"
        zone1d.preemptible = true
        zone1d.auto_restart = false
        zone1d.on_host_maintenance = "TERMINATE"
      end
    end
  end

  config.vm.define :wololo2 do |wololo2|
    wololo2.vm.provider :google do |google, override|
        google.google_project_id = "myproject"
        google.google_client_email = "mydevemail@developer.gserviceaccount.com"
        google.google_json_key_location = "mykeypath

      override.ssh.username = "temikus"
      override.ssh.private_key_path = "~/.ssh/id_rsa"

      google.zone = "europe-west1-d"

      google.zone_config "europe-west1-d" do |zone1d|
          zone1d.image = "debian-7-wheezy-v20150127"
          zone1d.zone = "europe-west1-d"
          zone1d.disk_type = "pd-ssd"
          zone1d.preemptible = true
          zone1d.auto_restart = false
          zone1d.on_host_maintenance = "TERMINATE"
      end
    end
  end
end
```
`vagrant up` results in a huge traceback:
```
temikus@vagrant-dev λ vagrant up
Your Gemfile lists the gem vagrant-google (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Vagrant appears to be running in a Bundler environment. Your
existing Gemfile will be used. Vagrant will not auto-load any plugins
installed with `vagrant plugin`. Vagrant will autoload any plugins in
the 'plugins' group in your Gemfile. You can force Vagrant to take over
with VAGRANT_FORCE_BUNDLER.

You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'wololo1' up with 'google' provider...
Bringing machine 'wololo2' up with 'google' provider...
==> wololo1: Launching an instance with the following settings...
==> wololo1:  -- Name:            i-2015071014
==> wololo1:  -- Type:            n1-standard-1
==> wololo1:  -- Disk type:       pd-ssd
==> wololo1:  -- Disk size:       10 GB
==> wololo1:  -- Disk name:
==> wololo1:  -- Image:           debian-7-wheezy-v20150127
==> wololo1:  -- Zone:            europe-west1-d
==> wololo1:  -- Network:         default
==> wololo1:  -- Metadata:        '{}'
==> wololo1:  -- Tags:            '[]'
==> wololo1:  -- IP Forward:
==> wololo1:  -- External IP:
==> wololo1:  -- Preemptible:     true
==> wololo1:  -- Auto Restart:    false
==> wololo1:  -- On Maintenance:  TERMINATE
==> wololo1:  -- Autodelete Disk: true
==> wololo1:  -- Scopes:
==> wololo2: Launching an instance with the following settings...
==> wololo2:  -- Name:            i-2015071014
==> wololo2:  -- Type:            n1-standard-1
==> wololo2:  -- Disk type:       pd-ssd
==> wololo2:  -- Disk size:       10 GB
==> wololo2:  -- Disk name:
==> wololo2:  -- Image:           debian-7-wheezy-v20150127
==> wololo2:  -- Zone:            europe-west1-d
==> wololo2:  -- Network:         default
==> wololo2:  -- Metadata:        '{}'
==> wololo2:  -- Tags:            '[]'
==> wololo2:  -- IP Forward:
==> wololo2:  -- External IP:
==> wololo2:  -- Preemptible:     true
==> wololo2:  -- Auto Restart:    false
==> wololo2:  -- On Maintenance:  TERMINATE
==> wololo2:  -- Autodelete Disk: true
==> wololo2:  -- Scopes:
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: already initialized constant Google::APIClient::Schema::Compute::V1::DiskAggregatedList
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: previous definition of DiskAggregatedList was here
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: already initialized constant Google::APIClient::Schema::Compute::V1::InstanceGroupAggregatedList
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: previous definition of InstanceGroupAggregatedList was here
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: already initialized constant Google::APIClient::Schema::Compute::V1::Region
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: previous definition of Region was here
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: already initialized constant Google::APIClient::Schema::Compute::V1::TargetReference
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/discovery/schema.rb:110: warning: previous definition of TargetReference was here
==> wololo2: An error occurred. The error will be shown after all tasks complete.
==> wololo1: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'wololo1' machine. Please report this as a bug:

The resource 'projects/dev-utility-90115/zones/europe-west1-d/disks/i-2015071014' already exists

/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google.rb:222:in `build_excon_response'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google.rb:193:in `request'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google/requests/compute/insert_disk.rb:108:in `insert_disk'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google/models/compute/disk.rb:40:in `save'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-core-1.32.0/lib/fog/core/collection.rb:51:in `create'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/run_instance.rb:104:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/warn_networks.rb:28:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/sync_folders.rb:33:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/provision.rb:80:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/call.rb:53:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/connect_google.rb:47:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:214:in `action_raw'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:191:in `block in action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/environment.rb:516:in `lock'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

An unexpected error occurred when executing the action on the
'wololo2' machine. Please report this as a bug:

The resource 'projects/dev-utility-90115/zones/europe-west1-d/disks/i-2015071014' already exists

/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google.rb:222:in `build_excon_response'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google.rb:193:in `request'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google/requests/compute/insert_disk.rb:108:in `insert_disk'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-google-0.0.7/lib/fog/google/models/compute/disk.rb:40:in `save'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/gems/fog-core-1.32.0/lib/fog/core/collection.rb:51:in `create'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/run_instance.rb:104:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/warn_networks.rb:28:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/sync_folders.rb:33:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/provision.rb:80:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/call.rb:53:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/code/vagrant-google/lib/vagrant-google/action/connect_google.rb:47:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/warden.rb:34:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/builder.rb:116:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `block in run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/util/busy.rb:19:in `busy'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/action/runner.rb:66:in `run'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:214:in `action_raw'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:191:in `block in action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/environment.rb:516:in `lock'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `call'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/machine.rb:178:in `action'
/home/temikus/.rbenv/versions/2.0.0-p598/lib/ruby/gems/2.0.0/bundler/gems/vagrant-27599ee897da/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by Temikus** [comment]
Fixed by #84
